name: nsg_login
description: A new Flutter package project.
# version: 0.0.1
homepage:
#publish_to: 'none'

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nsg_data:
    path: 
      ../nsg_data
  nsg_controls:
    path: 
      ../nsg_controls

  get: ^5.0.0-beta.52
  hovering: ^1.0.4
  flutter_multi_formatter: ^2.13.7
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  