name: nsg_login
description: A new Flutter package project.
# version: 0.0.1
homepage:
#publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nsg_data:
    path: 
      ../nsg_data
  nsg_controls:
    path: 
      ../nsg_controls
  hovering: ^1.0.4
  flutter_multi_formatter: ^2.6.2
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  