name: nsg_login
description: Визуальные компоненты для авторизации и регистрации пользователей в приложениях NSG. Поддерживает вход по телефону, email и паролю с SMS-верификацией.
version: 1.0.0-beta.1
homepage: https://github.com/zenalex/nsg_login
repository: https://github.com/zenalex/nsg_login
issue_tracker: https://github.com/zenalex/nsg_login/issues
documentation: https://github.com/zenalex/nsg_login
license: MIT
topics:
  - authentication
  - login
  - ui
  - widgets
  - forms
publish_to: 'none' # Раскомментируйте эту строку, если не хотите публиковать пакет

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # nsg_data: ^1.0.0
  # nsg_controls: ^1.0.0-beta.1
  nsg_data:
    path:
      ../nsg_data
  nsg_controls:
    path:
      ../nsg_controls

  get: ^5.0.0-beta.52
  hovering: ^1.0.4
  flutter_multi_formatter: ^2.13.10
  shared_preferences: ^2.0.6
  flutter_svg: ^2.2.0 
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
